package team.bishe.wms.mapper;


import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;
import team.bishe.wms.bean.Goods;
import team.bishe.wms.bean.GoodsExample;
import team.bishe.wms.bean.GoodsKey;
@Component

@Mapper
public interface GoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_w_goods_info
     *
     * @mbggenerated Wed Apr 22 16:55:10 CST 2020
     */
    int countByExample(GoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_w_goods_info
     *
     * @mbggenerated Wed Apr 22 16:55:10 CST 2020
     */
    int deleteByExample(GoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_w_goods_info
     *
     * @mbggenerated Wed Apr 22 16:55:10 CST 2020
     */
    int deleteByPrimaryKey(GoodsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_w_goods_info
     *
     * @mbggenerated Wed Apr 22 16:55:10 CST 2020
     */
    int insert(Goods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_w_goods_info
     *
     * @mbggenerated Wed Apr 22 16:55:10 CST 2020
     */
    int insertSelective(Goods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_w_goods_info
     *
     * @mbggenerated Wed Apr 22 16:55:10 CST 2020
     */
    List<Goods> selectByExample(GoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_w_goods_info
     *
     * @mbggenerated Wed Apr 22 16:55:10 CST 2020
     */
    Goods selectByPrimaryKey(GoodsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_w_goods_info
     *
     * @mbggenerated Wed Apr 22 16:55:10 CST 2020
     */
    int updateByExampleSelective(@Param("record") Goods record, @Param("example") GoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_w_goods_info
     *
     * @mbggenerated Wed Apr 22 16:55:10 CST 2020
     */
    int updateByExample(@Param("record") Goods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_w_goods_info
     *
     * @mbggenerated Wed Apr 22 16:55:10 CST 2020
     */
    int updateByPrimaryKeySelective(Goods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_w_goods_info
     *
     * @mbggenerated Wed Apr 22 16:55:10 CST 2020
     */
    int updateByPrimaryKey(Goods record);

}