package team.bishe.wms.mapper;


import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;
import team.bishe.wms.bean.StockOut;
import team.bishe.wms.bean.StockOutExample;
@Component

@Mapper
public interface StockOutMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stock_out
     *
     * @mbggenerated Wed Apr 22 16:55:10 CST 2020
     */
    int countByExample(StockOutExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stock_out
     *
     * @mbggenerated Wed Apr 22 16:55:10 CST 2020
     */
    int deleteByExample(StockOutExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stock_out
     *
     * @mbggenerated Wed Apr 22 16:55:10 CST 2020
     */
    int deleteByPrimaryKey(Integer rowid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stock_out
     *
     * @mbggenerated Wed Apr 22 16:55:10 CST 2020
     */
    int insert(StockOut record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stock_out
     *
     * @mbggenerated Wed Apr 22 16:55:10 CST 2020
     */
    int insertSelective(StockOut record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stock_out
     *
     * @mbggenerated Wed Apr 22 16:55:10 CST 2020
     */
    List<StockOut> selectByExample(StockOutExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stock_out
     *
     * @mbggenerated Wed Apr 22 16:55:10 CST 2020
     */
    StockOut selectByPrimaryKey(Integer rowid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stock_out
     *
     * @mbggenerated Wed Apr 22 16:55:10 CST 2020
     */
    int updateByExampleSelective(@Param("record") StockOut record, @Param("example") StockOutExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stock_out
     *
     * @mbggenerated Wed Apr 22 16:55:10 CST 2020
     */
    int updateByExample(@Param("record") StockOut record, @Param("example") StockOutExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stock_out
     *
     * @mbggenerated Wed Apr 22 16:55:10 CST 2020
     */
    int updateByPrimaryKeySelective(StockOut record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stock_out
     *
     * @mbggenerated Wed Apr 22 16:55:10 CST 2020
     */
    int updateByPrimaryKey(StockOut record);
}