package team.bishe.wms.mapper;


import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;
import team.bishe.wms.bean.StockChange;
import team.bishe.wms.bean.StockChangeExample;
@Component

@Mapper
public interface StockChangeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stock_change
     *
     * @mbggenerated Wed Apr 22 16:55:10 CST 2020
     */
    int countByExample(StockChangeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stock_change
     *
     * @mbggenerated Wed Apr 22 16:55:10 CST 2020
     */
    int deleteByExample(StockChangeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stock_change
     *
     * @mbggenerated Wed Apr 22 16:55:10 CST 2020
     */
    int deleteByPrimaryKey(Integer rowid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stock_change
     *
     * @mbggenerated Wed Apr 22 16:55:10 CST 2020
     */
    int insert(StockChange record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stock_change
     *
     * @mbggenerated Wed Apr 22 16:55:10 CST 2020
     */
    int insertSelective(StockChange record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stock_change
     *
     * @mbggenerated Wed Apr 22 16:55:10 CST 2020
     */
    List<StockChange> selectByExample(StockChangeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stock_change
     *
     * @mbggenerated Wed Apr 22 16:55:10 CST 2020
     */
    StockChange selectByPrimaryKey(Integer rowid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stock_change
     *
     * @mbggenerated Wed Apr 22 16:55:10 CST 2020
     */
    int updateByExampleSelective(@Param("record") StockChange record, @Param("example") StockChangeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stock_change
     *
     * @mbggenerated Wed Apr 22 16:55:10 CST 2020
     */
    int updateByExample(@Param("record") StockChange record, @Param("example") StockChangeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stock_change
     *
     * @mbggenerated Wed Apr 22 16:55:10 CST 2020
     */
    int updateByPrimaryKeySelective(StockChange record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stock_change
     *
     * @mbggenerated Wed Apr 22 16:55:10 CST 2020
     */
    int updateByPrimaryKey(StockChange record);
}