package team.bishe.wms.bean;

public class Customer {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.customer_id
     *
     * @mbggenerated Wed Apr 22 16:55:10 CST 2020
     */
    private Integer customerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.customer_name
     *
     * @mbggenerated Wed Apr 22 16:55:10 CST 2020
     */
    private String customerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.customer_gender
     *
     * @mbggenerated Wed Apr 22 16:55:10 CST 2020
     */
    private String customerGender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.customer_icId
     *
     * @mbggenerated Wed Apr 22 16:55:10 CST 2020
     */
    private Integer customerIcid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.customer_telNumber
     *
     * @mbggenerated Wed Apr 22 16:55:10 CST 2020
     */
    private Integer customerTelnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.customer_phoneNumber
     *
     * @mbggenerated Wed Apr 22 16:55:10 CST 2020
     */
    private Integer customerPhonenumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.customer_email
     *
     * @mbggenerated Wed Apr 22 16:55:10 CST 2020
     */
    private String customerEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.customer_address
     *
     * @mbggenerated Wed Apr 22 16:55:10 CST 2020
     */
    private String customerAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.customer_tips
     *
     * @mbggenerated Wed Apr 22 16:55:10 CST 2020
     */
    private String customerTips;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.customer_status
     *
     * @mbggenerated Wed Apr 22 16:55:10 CST 2020
     */
    private String customerStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.customer_id
     *
     * @return the value of customer.customer_id
     *
     * @mbggenerated Wed Apr 22 16:55:10 CST 2020
     */
    public Integer getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.customer_id
     *
     * @param customerId the value for customer.customer_id
     *
     * @mbggenerated Wed Apr 22 16:55:10 CST 2020
     */
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.customer_name
     *
     * @return the value of customer.customer_name
     *
     * @mbggenerated Wed Apr 22 16:55:10 CST 2020
     */
    public String getCustomerName() {
        return customerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.customer_name
     *
     * @param customerName the value for customer.customer_name
     *
     * @mbggenerated Wed Apr 22 16:55:10 CST 2020
     */
    public void setCustomerName(String customerName) {
        this.customerName = customerName == null ? null : customerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.customer_gender
     *
     * @return the value of customer.customer_gender
     *
     * @mbggenerated Wed Apr 22 16:55:10 CST 2020
     */
    public String getCustomerGender() {
        return customerGender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.customer_gender
     *
     * @param customerGender the value for customer.customer_gender
     *
     * @mbggenerated Wed Apr 22 16:55:10 CST 2020
     */
    public void setCustomerGender(String customerGender) {
        this.customerGender = customerGender == null ? null : customerGender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.customer_icId
     *
     * @return the value of customer.customer_icId
     *
     * @mbggenerated Wed Apr 22 16:55:10 CST 2020
     */
    public Integer getCustomerIcid() {
        return customerIcid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.customer_icId
     *
     * @param customerIcid the value for customer.customer_icId
     *
     * @mbggenerated Wed Apr 22 16:55:10 CST 2020
     */
    public void setCustomerIcid(Integer customerIcid) {
        this.customerIcid = customerIcid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.customer_telNumber
     *
     * @return the value of customer.customer_telNumber
     *
     * @mbggenerated Wed Apr 22 16:55:10 CST 2020
     */
    public Integer getCustomerTelnumber() {
        return customerTelnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.customer_telNumber
     *
     * @param customerTelnumber the value for customer.customer_telNumber
     *
     * @mbggenerated Wed Apr 22 16:55:10 CST 2020
     */
    public void setCustomerTelnumber(Integer customerTelnumber) {
        this.customerTelnumber = customerTelnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.customer_phoneNumber
     *
     * @return the value of customer.customer_phoneNumber
     *
     * @mbggenerated Wed Apr 22 16:55:10 CST 2020
     */
    public Integer getCustomerPhonenumber() {
        return customerPhonenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.customer_phoneNumber
     *
     * @param customerPhonenumber the value for customer.customer_phoneNumber
     *
     * @mbggenerated Wed Apr 22 16:55:10 CST 2020
     */
    public void setCustomerPhonenumber(Integer customerPhonenumber) {
        this.customerPhonenumber = customerPhonenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.customer_email
     *
     * @return the value of customer.customer_email
     *
     * @mbggenerated Wed Apr 22 16:55:10 CST 2020
     */
    public String getCustomerEmail() {
        return customerEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.customer_email
     *
     * @param customerEmail the value for customer.customer_email
     *
     * @mbggenerated Wed Apr 22 16:55:10 CST 2020
     */
    public void setCustomerEmail(String customerEmail) {
        this.customerEmail = customerEmail == null ? null : customerEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.customer_address
     *
     * @return the value of customer.customer_address
     *
     * @mbggenerated Wed Apr 22 16:55:10 CST 2020
     */
    public String getCustomerAddress() {
        return customerAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.customer_address
     *
     * @param customerAddress the value for customer.customer_address
     *
     * @mbggenerated Wed Apr 22 16:55:10 CST 2020
     */
    public void setCustomerAddress(String customerAddress) {
        this.customerAddress = customerAddress == null ? null : customerAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.customer_tips
     *
     * @return the value of customer.customer_tips
     *
     * @mbggenerated Wed Apr 22 16:55:10 CST 2020
     */
    public String getCustomerTips() {
        return customerTips;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.customer_tips
     *
     * @param customerTips the value for customer.customer_tips
     *
     * @mbggenerated Wed Apr 22 16:55:10 CST 2020
     */
    public void setCustomerTips(String customerTips) {
        this.customerTips = customerTips == null ? null : customerTips.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.customer_status
     *
     * @return the value of customer.customer_status
     *
     * @mbggenerated Wed Apr 22 16:55:10 CST 2020
     */
    public String getCustomerStatus() {
        return customerStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.customer_status
     *
     * @param customerStatus the value for customer.customer_status
     *
     * @mbggenerated Wed Apr 22 16:55:10 CST 2020
     */
    public void setCustomerStatus(String customerStatus) {
        this.customerStatus = customerStatus == null ? null : customerStatus.trim();
    }
}