package team.bishe.wms.bean;

public class GoodsKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_w_goods_info.good_id
     *
     * @mbggenerated Wed Apr 22 16:55:10 CST 2020
     */
    private String goodId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_w_goods_info.good_user_id
     *
     * @mbggenerated Wed Apr 22 16:55:10 CST 2020
     */
    private String goodUserId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_w_goods_info.good_id
     *
     * @return the value of t_w_goods_info.good_id
     *
     * @mbggenerated Wed Apr 22 16:55:10 CST 2020
     */
    public String getGoodId() {
        return goodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_w_goods_info.good_id
     *
     * @param goodId the value for t_w_goods_info.good_id
     *
     * @mbggenerated Wed Apr 22 16:55:10 CST 2020
     */
    public void setGoodId(String goodId) {
        this.goodId = goodId == null ? null : goodId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_w_goods_info.good_user_id
     *
     * @return the value of t_w_goods_info.good_user_id
     *
     * @mbggenerated Wed Apr 22 16:55:10 CST 2020
     */
    public String getGoodUserId() {
        return goodUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_w_goods_info.good_user_id
     *
     * @param goodUserId the value for t_w_goods_info.good_user_id
     *
     * @mbggenerated Wed Apr 22 16:55:10 CST 2020
     */
    public void setGoodUserId(String goodUserId) {
        this.goodUserId = goodUserId == null ? null : goodUserId.trim();
    }
}