package team.bishe.wms.bean;

public class Goods extends GoodsKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_w_goods_info.good_nm
     *
     * @mbggenerated Wed Apr 22 16:55:10 CST 2020
     */
    private String goodNm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_w_goods_info.good_unit
     *
     * @mbggenerated Wed Apr 22 16:55:10 CST 2020
     */
    private String goodUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_w_goods_info.good_spec
     *
     * @mbggenerated Wed Apr 22 16:55:10 CST 2020
     */
    private String goodSpec;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_w_goods_info.good_user
     *
     * @mbggenerated Wed Apr 22 16:55:10 CST 2020
     */
    private String goodUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_w_goods_info.type
     *
     * @mbggenerated Wed Apr 22 16:55:10 CST 2020
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_w_goods_info.region
     *
     * @mbggenerated Wed Apr 22 16:55:10 CST 2020
     */
    private String region;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_w_goods_info.number
     *
     * @mbggenerated Wed Apr 22 16:55:10 CST 2020
     */
    private Integer number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_w_goods_info.date_product
     *
     * @mbggenerated Wed Apr 22 16:55:10 CST 2020
     */
    private String dateProduct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_w_goods_info.date
     *
     * @mbggenerated Wed Apr 22 16:55:10 CST 2020
     */
    private Integer date;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_w_goods_info.good_nm
     *
     * @return the value of t_w_goods_info.good_nm
     *
     * @mbggenerated Wed Apr 22 16:55:10 CST 2020
     */
    public String getGoodNm() {
        return goodNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_w_goods_info.good_nm
     *
     * @param goodNm the value for t_w_goods_info.good_nm
     *
     * @mbggenerated Wed Apr 22 16:55:10 CST 2020
     */
    public void setGoodNm(String goodNm) {
        this.goodNm = goodNm == null ? null : goodNm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_w_goods_info.good_unit
     *
     * @return the value of t_w_goods_info.good_unit
     *
     * @mbggenerated Wed Apr 22 16:55:10 CST 2020
     */
    public String getGoodUnit() {
        return goodUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_w_goods_info.good_unit
     *
     * @param goodUnit the value for t_w_goods_info.good_unit
     *
     * @mbggenerated Wed Apr 22 16:55:10 CST 2020
     */
    public void setGoodUnit(String goodUnit) {
        this.goodUnit = goodUnit == null ? null : goodUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_w_goods_info.good_spec
     *
     * @return the value of t_w_goods_info.good_spec
     *
     * @mbggenerated Wed Apr 22 16:55:10 CST 2020
     */
    public String getGoodSpec() {
        return goodSpec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_w_goods_info.good_spec
     *
     * @param goodSpec the value for t_w_goods_info.good_spec
     *
     * @mbggenerated Wed Apr 22 16:55:10 CST 2020
     */
    public void setGoodSpec(String goodSpec) {
        this.goodSpec = goodSpec == null ? null : goodSpec.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_w_goods_info.good_user
     *
     * @return the value of t_w_goods_info.good_user
     *
     * @mbggenerated Wed Apr 22 16:55:10 CST 2020
     */
    public String getGoodUser() {
        return goodUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_w_goods_info.good_user
     *
     * @param goodUser the value for t_w_goods_info.good_user
     *
     * @mbggenerated Wed Apr 22 16:55:10 CST 2020
     */
    public void setGoodUser(String goodUser) {
        this.goodUser = goodUser == null ? null : goodUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_w_goods_info.type
     *
     * @return the value of t_w_goods_info.type
     *
     * @mbggenerated Wed Apr 22 16:55:10 CST 2020
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_w_goods_info.type
     *
     * @param type the value for t_w_goods_info.type
     *
     * @mbggenerated Wed Apr 22 16:55:10 CST 2020
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_w_goods_info.region
     *
     * @return the value of t_w_goods_info.region
     *
     * @mbggenerated Wed Apr 22 16:55:10 CST 2020
     */
    public String getRegion() {
        return region;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_w_goods_info.region
     *
     * @param region the value for t_w_goods_info.region
     *
     * @mbggenerated Wed Apr 22 16:55:10 CST 2020
     */
    public void setRegion(String region) {
        this.region = region == null ? null : region.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_w_goods_info.number
     *
     * @return the value of t_w_goods_info.number
     *
     * @mbggenerated Wed Apr 22 16:55:10 CST 2020
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_w_goods_info.number
     *
     * @param number the value for t_w_goods_info.number
     *
     * @mbggenerated Wed Apr 22 16:55:10 CST 2020
     */
    public void setNumber(Integer number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_w_goods_info.date_product
     *
     * @return the value of t_w_goods_info.date_product
     *
     * @mbggenerated Wed Apr 22 16:55:10 CST 2020
     */
    public String getDateProduct() {
        return dateProduct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_w_goods_info.date_product
     *
     * @param dateProduct the value for t_w_goods_info.date_product
     *
     * @mbggenerated Wed Apr 22 16:55:10 CST 2020
     */
    public void setDateProduct(String dateProduct) {
        this.dateProduct = dateProduct == null ? null : dateProduct.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_w_goods_info.date
     *
     * @return the value of t_w_goods_info.date
     *
     * @mbggenerated Wed Apr 22 16:55:10 CST 2020
     */
    public Integer getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_w_goods_info.date
     *
     * @param date the value for t_w_goods_info.date
     *
     * @mbggenerated Wed Apr 22 16:55:10 CST 2020
     */
    public void setDate(Integer date) {
        this.date = date;
    }
}