package team.bishe.wms.bean;

import java.util.Date;

public class StockChange {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stock_change.rowid
     *
     * @mbggenerated Wed Apr 22 20:10:30 CST 2020
     */
    private Integer rowid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stock_change.company_id
     *
     * @mbggenerated Wed Apr 22 20:10:30 CST 2020
     */
    private String companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stock_change.change_ws_no
     *
     * @mbggenerated Wed Apr 22 20:10:30 CST 2020
     */
    private String changeWsNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stock_change.change_ws_time
     *
     * @mbggenerated Wed Apr 22 20:10:30 CST 2020
     */
    private Date changeWsTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stock_change.old_customer_id
     *
     * @mbggenerated Wed Apr 22 20:10:30 CST 2020
     */
    private String oldCustomerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stock_change.old_customer_name
     *
     * @mbggenerated Wed Apr 22 20:10:30 CST 2020
     */
    private String oldCustomerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stock_change.new_customer_id
     *
     * @mbggenerated Wed Apr 22 20:10:30 CST 2020
     */
    private String newCustomerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stock_change.new_customer_name
     *
     * @mbggenerated Wed Apr 22 20:10:30 CST 2020
     */
    private String newCustomerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stock_change.tallyman
     *
     * @mbggenerated Wed Apr 22 20:10:30 CST 2020
     */
    private String tallyman;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stock_change.total_weight
     *
     * @mbggenerated Wed Apr 22 20:10:30 CST 2020
     */
    private Integer totalWeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stock_change.total_package_num
     *
     * @mbggenerated Wed Apr 22 20:10:30 CST 2020
     */
    private Integer totalPackageNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stock_change.remark
     *
     * @mbggenerated Wed Apr 22 20:10:30 CST 2020
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stock_change.status
     *
     * @mbggenerated Wed Apr 22 20:10:30 CST 2020
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stock_change.create_code
     *
     * @mbggenerated Wed Apr 22 20:10:30 CST 2020
     */
    private String createCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stock_change.create_date
     *
     * @mbggenerated Wed Apr 22 20:10:30 CST 2020
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stock_change.update_code
     *
     * @mbggenerated Wed Apr 22 20:10:30 CST 2020
     */
    private String updateCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stock_change.update_date
     *
     * @mbggenerated Wed Apr 22 20:10:30 CST 2020
     */
    private String updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stock_change.good_id
     *
     * @mbggenerated Wed Apr 22 20:10:30 CST 2020
     */
    private String goodId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stock_change.rowid
     *
     * @return the value of t_stock_change.rowid
     *
     * @mbggenerated Wed Apr 22 20:10:30 CST 2020
     */
    public Integer getRowid() {
        return rowid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stock_change.rowid
     *
     * @param rowid the value for t_stock_change.rowid
     *
     * @mbggenerated Wed Apr 22 20:10:30 CST 2020
     */
    public void setRowid(Integer rowid) {
        this.rowid = rowid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stock_change.company_id
     *
     * @return the value of t_stock_change.company_id
     *
     * @mbggenerated Wed Apr 22 20:10:30 CST 2020
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stock_change.company_id
     *
     * @param companyId the value for t_stock_change.company_id
     *
     * @mbggenerated Wed Apr 22 20:10:30 CST 2020
     */
    public void setCompanyId(String companyId) {
        this.companyId = companyId == null ? null : companyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stock_change.change_ws_no
     *
     * @return the value of t_stock_change.change_ws_no
     *
     * @mbggenerated Wed Apr 22 20:10:30 CST 2020
     */
    public String getChangeWsNo() {
        return changeWsNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stock_change.change_ws_no
     *
     * @param changeWsNo the value for t_stock_change.change_ws_no
     *
     * @mbggenerated Wed Apr 22 20:10:30 CST 2020
     */
    public void setChangeWsNo(String changeWsNo) {
        this.changeWsNo = changeWsNo == null ? null : changeWsNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stock_change.change_ws_time
     *
     * @return the value of t_stock_change.change_ws_time
     *
     * @mbggenerated Wed Apr 22 20:10:30 CST 2020
     */
    public Date getChangeWsTime() {
        return changeWsTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stock_change.change_ws_time
     *
     * @param changeWsTime the value for t_stock_change.change_ws_time
     *
     * @mbggenerated Wed Apr 22 20:10:30 CST 2020
     */
    public void setChangeWsTime(Date changeWsTime) {
        this.changeWsTime = changeWsTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stock_change.old_customer_id
     *
     * @return the value of t_stock_change.old_customer_id
     *
     * @mbggenerated Wed Apr 22 20:10:30 CST 2020
     */
    public String getOldCustomerId() {
        return oldCustomerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stock_change.old_customer_id
     *
     * @param oldCustomerId the value for t_stock_change.old_customer_id
     *
     * @mbggenerated Wed Apr 22 20:10:30 CST 2020
     */
    public void setOldCustomerId(String oldCustomerId) {
        this.oldCustomerId = oldCustomerId == null ? null : oldCustomerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stock_change.old_customer_name
     *
     * @return the value of t_stock_change.old_customer_name
     *
     * @mbggenerated Wed Apr 22 20:10:30 CST 2020
     */
    public String getOldCustomerName() {
        return oldCustomerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stock_change.old_customer_name
     *
     * @param oldCustomerName the value for t_stock_change.old_customer_name
     *
     * @mbggenerated Wed Apr 22 20:10:30 CST 2020
     */
    public void setOldCustomerName(String oldCustomerName) {
        this.oldCustomerName = oldCustomerName == null ? null : oldCustomerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stock_change.new_customer_id
     *
     * @return the value of t_stock_change.new_customer_id
     *
     * @mbggenerated Wed Apr 22 20:10:30 CST 2020
     */
    public String getNewCustomerId() {
        return newCustomerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stock_change.new_customer_id
     *
     * @param newCustomerId the value for t_stock_change.new_customer_id
     *
     * @mbggenerated Wed Apr 22 20:10:30 CST 2020
     */
    public void setNewCustomerId(String newCustomerId) {
        this.newCustomerId = newCustomerId == null ? null : newCustomerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stock_change.new_customer_name
     *
     * @return the value of t_stock_change.new_customer_name
     *
     * @mbggenerated Wed Apr 22 20:10:30 CST 2020
     */
    public String getNewCustomerName() {
        return newCustomerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stock_change.new_customer_name
     *
     * @param newCustomerName the value for t_stock_change.new_customer_name
     *
     * @mbggenerated Wed Apr 22 20:10:30 CST 2020
     */
    public void setNewCustomerName(String newCustomerName) {
        this.newCustomerName = newCustomerName == null ? null : newCustomerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stock_change.tallyman
     *
     * @return the value of t_stock_change.tallyman
     *
     * @mbggenerated Wed Apr 22 20:10:30 CST 2020
     */
    public String getTallyman() {
        return tallyman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stock_change.tallyman
     *
     * @param tallyman the value for t_stock_change.tallyman
     *
     * @mbggenerated Wed Apr 22 20:10:30 CST 2020
     */
    public void setTallyman(String tallyman) {
        this.tallyman = tallyman == null ? null : tallyman.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stock_change.total_weight
     *
     * @return the value of t_stock_change.total_weight
     *
     * @mbggenerated Wed Apr 22 20:10:30 CST 2020
     */
    public Integer getTotalWeight() {
        return totalWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stock_change.total_weight
     *
     * @param totalWeight the value for t_stock_change.total_weight
     *
     * @mbggenerated Wed Apr 22 20:10:30 CST 2020
     */
    public void setTotalWeight(Integer totalWeight) {
        this.totalWeight = totalWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stock_change.total_package_num
     *
     * @return the value of t_stock_change.total_package_num
     *
     * @mbggenerated Wed Apr 22 20:10:30 CST 2020
     */
    public Integer getTotalPackageNum() {
        return totalPackageNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stock_change.total_package_num
     *
     * @param totalPackageNum the value for t_stock_change.total_package_num
     *
     * @mbggenerated Wed Apr 22 20:10:30 CST 2020
     */
    public void setTotalPackageNum(Integer totalPackageNum) {
        this.totalPackageNum = totalPackageNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stock_change.remark
     *
     * @return the value of t_stock_change.remark
     *
     * @mbggenerated Wed Apr 22 20:10:30 CST 2020
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stock_change.remark
     *
     * @param remark the value for t_stock_change.remark
     *
     * @mbggenerated Wed Apr 22 20:10:30 CST 2020
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stock_change.status
     *
     * @return the value of t_stock_change.status
     *
     * @mbggenerated Wed Apr 22 20:10:30 CST 2020
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stock_change.status
     *
     * @param status the value for t_stock_change.status
     *
     * @mbggenerated Wed Apr 22 20:10:30 CST 2020
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stock_change.create_code
     *
     * @return the value of t_stock_change.create_code
     *
     * @mbggenerated Wed Apr 22 20:10:30 CST 2020
     */
    public String getCreateCode() {
        return createCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stock_change.create_code
     *
     * @param createCode the value for t_stock_change.create_code
     *
     * @mbggenerated Wed Apr 22 20:10:30 CST 2020
     */
    public void setCreateCode(String createCode) {
        this.createCode = createCode == null ? null : createCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stock_change.create_date
     *
     * @return the value of t_stock_change.create_date
     *
     * @mbggenerated Wed Apr 22 20:10:30 CST 2020
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stock_change.create_date
     *
     * @param createDate the value for t_stock_change.create_date
     *
     * @mbggenerated Wed Apr 22 20:10:30 CST 2020
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stock_change.update_code
     *
     * @return the value of t_stock_change.update_code
     *
     * @mbggenerated Wed Apr 22 20:10:30 CST 2020
     */
    public String getUpdateCode() {
        return updateCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stock_change.update_code
     *
     * @param updateCode the value for t_stock_change.update_code
     *
     * @mbggenerated Wed Apr 22 20:10:30 CST 2020
     */
    public void setUpdateCode(String updateCode) {
        this.updateCode = updateCode == null ? null : updateCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stock_change.update_date
     *
     * @return the value of t_stock_change.update_date
     *
     * @mbggenerated Wed Apr 22 20:10:30 CST 2020
     */
    public String getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stock_change.update_date
     *
     * @param updateDate the value for t_stock_change.update_date
     *
     * @mbggenerated Wed Apr 22 20:10:30 CST 2020
     */
    public void setUpdateDate(String updateDate) {
        this.updateDate = updateDate == null ? null : updateDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stock_change.good_id
     *
     * @return the value of t_stock_change.good_id
     *
     * @mbggenerated Wed Apr 22 20:10:30 CST 2020
     */
    public String getGoodId() {
        return goodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stock_change.good_id
     *
     * @param goodId the value for t_stock_change.good_id
     *
     * @mbggenerated Wed Apr 22 20:10:30 CST 2020
     */
    public void setGoodId(String goodId) {
        this.goodId = goodId == null ? null : goodId.trim();
    }
}