package team.bishe.wms.bean;

import java.util.Date;

public class StockOut {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stock_out.rowid
     *
     * @mbggenerated Wed Apr 22 20:10:30 CST 2020
     */
    private Integer rowid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stock_out.company_id
     *
     * @mbggenerated Wed Apr 22 20:10:30 CST 2020
     */
    private String companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stock_out.out_ws_no
     *
     * @mbggenerated Wed Apr 22 20:10:30 CST 2020
     */
    private String outWsNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stock_out.out_ws_time
     *
     * @mbggenerated Wed Apr 22 20:10:30 CST 2020
     */
    private Date outWsTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stock_out.customer_id
     *
     * @mbggenerated Wed Apr 22 20:10:30 CST 2020
     */
    private Integer customerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stock_out.customer_name
     *
     * @mbggenerated Wed Apr 22 20:10:30 CST 2020
     */
    private String customerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stock_out.tallyman
     *
     * @mbggenerated Wed Apr 22 20:10:30 CST 2020
     */
    private String tallyman;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stock_out.total_weight
     *
     * @mbggenerated Wed Apr 22 20:10:30 CST 2020
     */
    private Integer totalWeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stock_out.total_package_num
     *
     * @mbggenerated Wed Apr 22 20:10:30 CST 2020
     */
    private Integer totalPackageNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stock_out.remark
     *
     * @mbggenerated Wed Apr 22 20:10:30 CST 2020
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stock_out.status
     *
     * @mbggenerated Wed Apr 22 20:10:30 CST 2020
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stock_out.create_code
     *
     * @mbggenerated Wed Apr 22 20:10:30 CST 2020
     */
    private String createCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stock_out.create_date
     *
     * @mbggenerated Wed Apr 22 20:10:30 CST 2020
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stock_out.update_code
     *
     * @mbggenerated Wed Apr 22 20:10:30 CST 2020
     */
    private String updateCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stock_out.update_date
     *
     * @mbggenerated Wed Apr 22 20:10:30 CST 2020
     */
    private String updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stock_out.good_id
     *
     * @mbggenerated Wed Apr 22 20:10:30 CST 2020
     */
    private String goodId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stock_out.whouse_id
     *
     * @mbggenerated Wed Apr 22 20:10:30 CST 2020
     */
    private String whouseId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stock_out.rowid
     *
     * @return the value of t_stock_out.rowid
     *
     * @mbggenerated Wed Apr 22 20:10:30 CST 2020
     */
    public Integer getRowid() {
        return rowid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stock_out.rowid
     *
     * @param rowid the value for t_stock_out.rowid
     *
     * @mbggenerated Wed Apr 22 20:10:30 CST 2020
     */
    public void setRowid(Integer rowid) {
        this.rowid = rowid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stock_out.company_id
     *
     * @return the value of t_stock_out.company_id
     *
     * @mbggenerated Wed Apr 22 20:10:30 CST 2020
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stock_out.company_id
     *
     * @param companyId the value for t_stock_out.company_id
     *
     * @mbggenerated Wed Apr 22 20:10:30 CST 2020
     */
    public void setCompanyId(String companyId) {
        this.companyId = companyId == null ? null : companyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stock_out.out_ws_no
     *
     * @return the value of t_stock_out.out_ws_no
     *
     * @mbggenerated Wed Apr 22 20:10:30 CST 2020
     */
    public String getOutWsNo() {
        return outWsNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stock_out.out_ws_no
     *
     * @param outWsNo the value for t_stock_out.out_ws_no
     *
     * @mbggenerated Wed Apr 22 20:10:30 CST 2020
     */
    public void setOutWsNo(String outWsNo) {
        this.outWsNo = outWsNo == null ? null : outWsNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stock_out.out_ws_time
     *
     * @return the value of t_stock_out.out_ws_time
     *
     * @mbggenerated Wed Apr 22 20:10:30 CST 2020
     */
    public Date getOutWsTime() {
        return outWsTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stock_out.out_ws_time
     *
     * @param outWsTime the value for t_stock_out.out_ws_time
     *
     * @mbggenerated Wed Apr 22 20:10:30 CST 2020
     */
    public void setOutWsTime(Date outWsTime) {
        this.outWsTime = outWsTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stock_out.customer_id
     *
     * @return the value of t_stock_out.customer_id
     *
     * @mbggenerated Wed Apr 22 20:10:30 CST 2020
     */
    public Integer getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stock_out.customer_id
     *
     * @param customerId the value for t_stock_out.customer_id
     *
     * @mbggenerated Wed Apr 22 20:10:30 CST 2020
     */
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stock_out.customer_name
     *
     * @return the value of t_stock_out.customer_name
     *
     * @mbggenerated Wed Apr 22 20:10:30 CST 2020
     */
    public String getCustomerName() {
        return customerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stock_out.customer_name
     *
     * @param customerName the value for t_stock_out.customer_name
     *
     * @mbggenerated Wed Apr 22 20:10:30 CST 2020
     */
    public void setCustomerName(String customerName) {
        this.customerName = customerName == null ? null : customerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stock_out.tallyman
     *
     * @return the value of t_stock_out.tallyman
     *
     * @mbggenerated Wed Apr 22 20:10:30 CST 2020
     */
    public String getTallyman() {
        return tallyman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stock_out.tallyman
     *
     * @param tallyman the value for t_stock_out.tallyman
     *
     * @mbggenerated Wed Apr 22 20:10:30 CST 2020
     */
    public void setTallyman(String tallyman) {
        this.tallyman = tallyman == null ? null : tallyman.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stock_out.total_weight
     *
     * @return the value of t_stock_out.total_weight
     *
     * @mbggenerated Wed Apr 22 20:10:30 CST 2020
     */
    public Integer getTotalWeight() {
        return totalWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stock_out.total_weight
     *
     * @param totalWeight the value for t_stock_out.total_weight
     *
     * @mbggenerated Wed Apr 22 20:10:30 CST 2020
     */
    public void setTotalWeight(Integer totalWeight) {
        this.totalWeight = totalWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stock_out.total_package_num
     *
     * @return the value of t_stock_out.total_package_num
     *
     * @mbggenerated Wed Apr 22 20:10:30 CST 2020
     */
    public Integer getTotalPackageNum() {
        return totalPackageNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stock_out.total_package_num
     *
     * @param totalPackageNum the value for t_stock_out.total_package_num
     *
     * @mbggenerated Wed Apr 22 20:10:30 CST 2020
     */
    public void setTotalPackageNum(Integer totalPackageNum) {
        this.totalPackageNum = totalPackageNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stock_out.remark
     *
     * @return the value of t_stock_out.remark
     *
     * @mbggenerated Wed Apr 22 20:10:30 CST 2020
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stock_out.remark
     *
     * @param remark the value for t_stock_out.remark
     *
     * @mbggenerated Wed Apr 22 20:10:30 CST 2020
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stock_out.status
     *
     * @return the value of t_stock_out.status
     *
     * @mbggenerated Wed Apr 22 20:10:30 CST 2020
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stock_out.status
     *
     * @param status the value for t_stock_out.status
     *
     * @mbggenerated Wed Apr 22 20:10:30 CST 2020
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stock_out.create_code
     *
     * @return the value of t_stock_out.create_code
     *
     * @mbggenerated Wed Apr 22 20:10:30 CST 2020
     */
    public String getCreateCode() {
        return createCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stock_out.create_code
     *
     * @param createCode the value for t_stock_out.create_code
     *
     * @mbggenerated Wed Apr 22 20:10:30 CST 2020
     */
    public void setCreateCode(String createCode) {
        this.createCode = createCode == null ? null : createCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stock_out.create_date
     *
     * @return the value of t_stock_out.create_date
     *
     * @mbggenerated Wed Apr 22 20:10:30 CST 2020
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stock_out.create_date
     *
     * @param createDate the value for t_stock_out.create_date
     *
     * @mbggenerated Wed Apr 22 20:10:30 CST 2020
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stock_out.update_code
     *
     * @return the value of t_stock_out.update_code
     *
     * @mbggenerated Wed Apr 22 20:10:30 CST 2020
     */
    public String getUpdateCode() {
        return updateCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stock_out.update_code
     *
     * @param updateCode the value for t_stock_out.update_code
     *
     * @mbggenerated Wed Apr 22 20:10:30 CST 2020
     */
    public void setUpdateCode(String updateCode) {
        this.updateCode = updateCode == null ? null : updateCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stock_out.update_date
     *
     * @return the value of t_stock_out.update_date
     *
     * @mbggenerated Wed Apr 22 20:10:30 CST 2020
     */
    public String getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stock_out.update_date
     *
     * @param updateDate the value for t_stock_out.update_date
     *
     * @mbggenerated Wed Apr 22 20:10:30 CST 2020
     */
    public void setUpdateDate(String updateDate) {
        this.updateDate = updateDate == null ? null : updateDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stock_out.good_id
     *
     * @return the value of t_stock_out.good_id
     *
     * @mbggenerated Wed Apr 22 20:10:30 CST 2020
     */
    public String getGoodId() {
        return goodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stock_out.good_id
     *
     * @param goodId the value for t_stock_out.good_id
     *
     * @mbggenerated Wed Apr 22 20:10:30 CST 2020
     */
    public void setGoodId(String goodId) {
        this.goodId = goodId == null ? null : goodId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stock_out.whouse_id
     *
     * @return the value of t_stock_out.whouse_id
     *
     * @mbggenerated Wed Apr 22 20:10:30 CST 2020
     */
    public String getWhouseId() {
        return whouseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stock_out.whouse_id
     *
     * @param whouseId the value for t_stock_out.whouse_id
     *
     * @mbggenerated Wed Apr 22 20:10:30 CST 2020
     */
    public void setWhouseId(String whouseId) {
        this.whouseId = whouseId == null ? null : whouseId.trim();
    }
}