package team.bishe.wms.bean;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class StockChangeExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_stock_change
     *
     * @mbggenerated Wed Apr 22 20:10:30 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_stock_change
     *
     * @mbggenerated Wed Apr 22 20:10:30 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_stock_change
     *
     * @mbggenerated Wed Apr 22 20:10:30 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stock_change
     *
     * @mbggenerated Wed Apr 22 20:10:30 CST 2020
     */
    public StockChangeExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stock_change
     *
     * @mbggenerated Wed Apr 22 20:10:30 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stock_change
     *
     * @mbggenerated Wed Apr 22 20:10:30 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stock_change
     *
     * @mbggenerated Wed Apr 22 20:10:30 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stock_change
     *
     * @mbggenerated Wed Apr 22 20:10:30 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stock_change
     *
     * @mbggenerated Wed Apr 22 20:10:30 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stock_change
     *
     * @mbggenerated Wed Apr 22 20:10:30 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stock_change
     *
     * @mbggenerated Wed Apr 22 20:10:30 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stock_change
     *
     * @mbggenerated Wed Apr 22 20:10:30 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stock_change
     *
     * @mbggenerated Wed Apr 22 20:10:30 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stock_change
     *
     * @mbggenerated Wed Apr 22 20:10:30 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_stock_change
     *
     * @mbggenerated Wed Apr 22 20:10:30 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andRowidIsNull() {
            addCriterion("rowid is null");
            return (Criteria) this;
        }

        public Criteria andRowidIsNotNull() {
            addCriterion("rowid is not null");
            return (Criteria) this;
        }

        public Criteria andRowidEqualTo(Integer value) {
            addCriterion("rowid =", value, "rowid");
            return (Criteria) this;
        }

        public Criteria andRowidNotEqualTo(Integer value) {
            addCriterion("rowid <>", value, "rowid");
            return (Criteria) this;
        }

        public Criteria andRowidGreaterThan(Integer value) {
            addCriterion("rowid >", value, "rowid");
            return (Criteria) this;
        }

        public Criteria andRowidGreaterThanOrEqualTo(Integer value) {
            addCriterion("rowid >=", value, "rowid");
            return (Criteria) this;
        }

        public Criteria andRowidLessThan(Integer value) {
            addCriterion("rowid <", value, "rowid");
            return (Criteria) this;
        }

        public Criteria andRowidLessThanOrEqualTo(Integer value) {
            addCriterion("rowid <=", value, "rowid");
            return (Criteria) this;
        }

        public Criteria andRowidIn(List<Integer> values) {
            addCriterion("rowid in", values, "rowid");
            return (Criteria) this;
        }

        public Criteria andRowidNotIn(List<Integer> values) {
            addCriterion("rowid not in", values, "rowid");
            return (Criteria) this;
        }

        public Criteria andRowidBetween(Integer value1, Integer value2) {
            addCriterion("rowid between", value1, value2, "rowid");
            return (Criteria) this;
        }

        public Criteria andRowidNotBetween(Integer value1, Integer value2) {
            addCriterion("rowid not between", value1, value2, "rowid");
            return (Criteria) this;
        }

        public Criteria andCompanyIdIsNull() {
            addCriterion("company_id is null");
            return (Criteria) this;
        }

        public Criteria andCompanyIdIsNotNull() {
            addCriterion("company_id is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyIdEqualTo(String value) {
            addCriterion("company_id =", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdNotEqualTo(String value) {
            addCriterion("company_id <>", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdGreaterThan(String value) {
            addCriterion("company_id >", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdGreaterThanOrEqualTo(String value) {
            addCriterion("company_id >=", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdLessThan(String value) {
            addCriterion("company_id <", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdLessThanOrEqualTo(String value) {
            addCriterion("company_id <=", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdLike(String value) {
            addCriterion("company_id like", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdNotLike(String value) {
            addCriterion("company_id not like", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdIn(List<String> values) {
            addCriterion("company_id in", values, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdNotIn(List<String> values) {
            addCriterion("company_id not in", values, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdBetween(String value1, String value2) {
            addCriterion("company_id between", value1, value2, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdNotBetween(String value1, String value2) {
            addCriterion("company_id not between", value1, value2, "companyId");
            return (Criteria) this;
        }

        public Criteria andChangeWsNoIsNull() {
            addCriterion("change_ws_no is null");
            return (Criteria) this;
        }

        public Criteria andChangeWsNoIsNotNull() {
            addCriterion("change_ws_no is not null");
            return (Criteria) this;
        }

        public Criteria andChangeWsNoEqualTo(String value) {
            addCriterion("change_ws_no =", value, "changeWsNo");
            return (Criteria) this;
        }

        public Criteria andChangeWsNoNotEqualTo(String value) {
            addCriterion("change_ws_no <>", value, "changeWsNo");
            return (Criteria) this;
        }

        public Criteria andChangeWsNoGreaterThan(String value) {
            addCriterion("change_ws_no >", value, "changeWsNo");
            return (Criteria) this;
        }

        public Criteria andChangeWsNoGreaterThanOrEqualTo(String value) {
            addCriterion("change_ws_no >=", value, "changeWsNo");
            return (Criteria) this;
        }

        public Criteria andChangeWsNoLessThan(String value) {
            addCriterion("change_ws_no <", value, "changeWsNo");
            return (Criteria) this;
        }

        public Criteria andChangeWsNoLessThanOrEqualTo(String value) {
            addCriterion("change_ws_no <=", value, "changeWsNo");
            return (Criteria) this;
        }

        public Criteria andChangeWsNoLike(String value) {
            addCriterion("change_ws_no like", value, "changeWsNo");
            return (Criteria) this;
        }

        public Criteria andChangeWsNoNotLike(String value) {
            addCriterion("change_ws_no not like", value, "changeWsNo");
            return (Criteria) this;
        }

        public Criteria andChangeWsNoIn(List<String> values) {
            addCriterion("change_ws_no in", values, "changeWsNo");
            return (Criteria) this;
        }

        public Criteria andChangeWsNoNotIn(List<String> values) {
            addCriterion("change_ws_no not in", values, "changeWsNo");
            return (Criteria) this;
        }

        public Criteria andChangeWsNoBetween(String value1, String value2) {
            addCriterion("change_ws_no between", value1, value2, "changeWsNo");
            return (Criteria) this;
        }

        public Criteria andChangeWsNoNotBetween(String value1, String value2) {
            addCriterion("change_ws_no not between", value1, value2, "changeWsNo");
            return (Criteria) this;
        }

        public Criteria andChangeWsTimeIsNull() {
            addCriterion("change_ws_time is null");
            return (Criteria) this;
        }

        public Criteria andChangeWsTimeIsNotNull() {
            addCriterion("change_ws_time is not null");
            return (Criteria) this;
        }

        public Criteria andChangeWsTimeEqualTo(Date value) {
            addCriterion("change_ws_time =", value, "changeWsTime");
            return (Criteria) this;
        }

        public Criteria andChangeWsTimeNotEqualTo(Date value) {
            addCriterion("change_ws_time <>", value, "changeWsTime");
            return (Criteria) this;
        }

        public Criteria andChangeWsTimeGreaterThan(Date value) {
            addCriterion("change_ws_time >", value, "changeWsTime");
            return (Criteria) this;
        }

        public Criteria andChangeWsTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("change_ws_time >=", value, "changeWsTime");
            return (Criteria) this;
        }

        public Criteria andChangeWsTimeLessThan(Date value) {
            addCriterion("change_ws_time <", value, "changeWsTime");
            return (Criteria) this;
        }

        public Criteria andChangeWsTimeLessThanOrEqualTo(Date value) {
            addCriterion("change_ws_time <=", value, "changeWsTime");
            return (Criteria) this;
        }

        public Criteria andChangeWsTimeIn(List<Date> values) {
            addCriterion("change_ws_time in", values, "changeWsTime");
            return (Criteria) this;
        }

        public Criteria andChangeWsTimeNotIn(List<Date> values) {
            addCriterion("change_ws_time not in", values, "changeWsTime");
            return (Criteria) this;
        }

        public Criteria andChangeWsTimeBetween(Date value1, Date value2) {
            addCriterion("change_ws_time between", value1, value2, "changeWsTime");
            return (Criteria) this;
        }

        public Criteria andChangeWsTimeNotBetween(Date value1, Date value2) {
            addCriterion("change_ws_time not between", value1, value2, "changeWsTime");
            return (Criteria) this;
        }

        public Criteria andOldCustomerIdIsNull() {
            addCriterion("old_customer_id is null");
            return (Criteria) this;
        }

        public Criteria andOldCustomerIdIsNotNull() {
            addCriterion("old_customer_id is not null");
            return (Criteria) this;
        }

        public Criteria andOldCustomerIdEqualTo(String value) {
            addCriterion("old_customer_id =", value, "oldCustomerId");
            return (Criteria) this;
        }

        public Criteria andOldCustomerIdNotEqualTo(String value) {
            addCriterion("old_customer_id <>", value, "oldCustomerId");
            return (Criteria) this;
        }

        public Criteria andOldCustomerIdGreaterThan(String value) {
            addCriterion("old_customer_id >", value, "oldCustomerId");
            return (Criteria) this;
        }

        public Criteria andOldCustomerIdGreaterThanOrEqualTo(String value) {
            addCriterion("old_customer_id >=", value, "oldCustomerId");
            return (Criteria) this;
        }

        public Criteria andOldCustomerIdLessThan(String value) {
            addCriterion("old_customer_id <", value, "oldCustomerId");
            return (Criteria) this;
        }

        public Criteria andOldCustomerIdLessThanOrEqualTo(String value) {
            addCriterion("old_customer_id <=", value, "oldCustomerId");
            return (Criteria) this;
        }

        public Criteria andOldCustomerIdLike(String value) {
            addCriterion("old_customer_id like", value, "oldCustomerId");
            return (Criteria) this;
        }

        public Criteria andOldCustomerIdNotLike(String value) {
            addCriterion("old_customer_id not like", value, "oldCustomerId");
            return (Criteria) this;
        }

        public Criteria andOldCustomerIdIn(List<String> values) {
            addCriterion("old_customer_id in", values, "oldCustomerId");
            return (Criteria) this;
        }

        public Criteria andOldCustomerIdNotIn(List<String> values) {
            addCriterion("old_customer_id not in", values, "oldCustomerId");
            return (Criteria) this;
        }

        public Criteria andOldCustomerIdBetween(String value1, String value2) {
            addCriterion("old_customer_id between", value1, value2, "oldCustomerId");
            return (Criteria) this;
        }

        public Criteria andOldCustomerIdNotBetween(String value1, String value2) {
            addCriterion("old_customer_id not between", value1, value2, "oldCustomerId");
            return (Criteria) this;
        }

        public Criteria andOldCustomerNameIsNull() {
            addCriterion("old_customer_name is null");
            return (Criteria) this;
        }

        public Criteria andOldCustomerNameIsNotNull() {
            addCriterion("old_customer_name is not null");
            return (Criteria) this;
        }

        public Criteria andOldCustomerNameEqualTo(String value) {
            addCriterion("old_customer_name =", value, "oldCustomerName");
            return (Criteria) this;
        }

        public Criteria andOldCustomerNameNotEqualTo(String value) {
            addCriterion("old_customer_name <>", value, "oldCustomerName");
            return (Criteria) this;
        }

        public Criteria andOldCustomerNameGreaterThan(String value) {
            addCriterion("old_customer_name >", value, "oldCustomerName");
            return (Criteria) this;
        }

        public Criteria andOldCustomerNameGreaterThanOrEqualTo(String value) {
            addCriterion("old_customer_name >=", value, "oldCustomerName");
            return (Criteria) this;
        }

        public Criteria andOldCustomerNameLessThan(String value) {
            addCriterion("old_customer_name <", value, "oldCustomerName");
            return (Criteria) this;
        }

        public Criteria andOldCustomerNameLessThanOrEqualTo(String value) {
            addCriterion("old_customer_name <=", value, "oldCustomerName");
            return (Criteria) this;
        }

        public Criteria andOldCustomerNameLike(String value) {
            addCriterion("old_customer_name like", value, "oldCustomerName");
            return (Criteria) this;
        }

        public Criteria andOldCustomerNameNotLike(String value) {
            addCriterion("old_customer_name not like", value, "oldCustomerName");
            return (Criteria) this;
        }

        public Criteria andOldCustomerNameIn(List<String> values) {
            addCriterion("old_customer_name in", values, "oldCustomerName");
            return (Criteria) this;
        }

        public Criteria andOldCustomerNameNotIn(List<String> values) {
            addCriterion("old_customer_name not in", values, "oldCustomerName");
            return (Criteria) this;
        }

        public Criteria andOldCustomerNameBetween(String value1, String value2) {
            addCriterion("old_customer_name between", value1, value2, "oldCustomerName");
            return (Criteria) this;
        }

        public Criteria andOldCustomerNameNotBetween(String value1, String value2) {
            addCriterion("old_customer_name not between", value1, value2, "oldCustomerName");
            return (Criteria) this;
        }

        public Criteria andNewCustomerIdIsNull() {
            addCriterion("new_customer_id is null");
            return (Criteria) this;
        }

        public Criteria andNewCustomerIdIsNotNull() {
            addCriterion("new_customer_id is not null");
            return (Criteria) this;
        }

        public Criteria andNewCustomerIdEqualTo(String value) {
            addCriterion("new_customer_id =", value, "newCustomerId");
            return (Criteria) this;
        }

        public Criteria andNewCustomerIdNotEqualTo(String value) {
            addCriterion("new_customer_id <>", value, "newCustomerId");
            return (Criteria) this;
        }

        public Criteria andNewCustomerIdGreaterThan(String value) {
            addCriterion("new_customer_id >", value, "newCustomerId");
            return (Criteria) this;
        }

        public Criteria andNewCustomerIdGreaterThanOrEqualTo(String value) {
            addCriterion("new_customer_id >=", value, "newCustomerId");
            return (Criteria) this;
        }

        public Criteria andNewCustomerIdLessThan(String value) {
            addCriterion("new_customer_id <", value, "newCustomerId");
            return (Criteria) this;
        }

        public Criteria andNewCustomerIdLessThanOrEqualTo(String value) {
            addCriterion("new_customer_id <=", value, "newCustomerId");
            return (Criteria) this;
        }

        public Criteria andNewCustomerIdLike(String value) {
            addCriterion("new_customer_id like", value, "newCustomerId");
            return (Criteria) this;
        }

        public Criteria andNewCustomerIdNotLike(String value) {
            addCriterion("new_customer_id not like", value, "newCustomerId");
            return (Criteria) this;
        }

        public Criteria andNewCustomerIdIn(List<String> values) {
            addCriterion("new_customer_id in", values, "newCustomerId");
            return (Criteria) this;
        }

        public Criteria andNewCustomerIdNotIn(List<String> values) {
            addCriterion("new_customer_id not in", values, "newCustomerId");
            return (Criteria) this;
        }

        public Criteria andNewCustomerIdBetween(String value1, String value2) {
            addCriterion("new_customer_id between", value1, value2, "newCustomerId");
            return (Criteria) this;
        }

        public Criteria andNewCustomerIdNotBetween(String value1, String value2) {
            addCriterion("new_customer_id not between", value1, value2, "newCustomerId");
            return (Criteria) this;
        }

        public Criteria andNewCustomerNameIsNull() {
            addCriterion("new_customer_name is null");
            return (Criteria) this;
        }

        public Criteria andNewCustomerNameIsNotNull() {
            addCriterion("new_customer_name is not null");
            return (Criteria) this;
        }

        public Criteria andNewCustomerNameEqualTo(String value) {
            addCriterion("new_customer_name =", value, "newCustomerName");
            return (Criteria) this;
        }

        public Criteria andNewCustomerNameNotEqualTo(String value) {
            addCriterion("new_customer_name <>", value, "newCustomerName");
            return (Criteria) this;
        }

        public Criteria andNewCustomerNameGreaterThan(String value) {
            addCriterion("new_customer_name >", value, "newCustomerName");
            return (Criteria) this;
        }

        public Criteria andNewCustomerNameGreaterThanOrEqualTo(String value) {
            addCriterion("new_customer_name >=", value, "newCustomerName");
            return (Criteria) this;
        }

        public Criteria andNewCustomerNameLessThan(String value) {
            addCriterion("new_customer_name <", value, "newCustomerName");
            return (Criteria) this;
        }

        public Criteria andNewCustomerNameLessThanOrEqualTo(String value) {
            addCriterion("new_customer_name <=", value, "newCustomerName");
            return (Criteria) this;
        }

        public Criteria andNewCustomerNameLike(String value) {
            addCriterion("new_customer_name like", value, "newCustomerName");
            return (Criteria) this;
        }

        public Criteria andNewCustomerNameNotLike(String value) {
            addCriterion("new_customer_name not like", value, "newCustomerName");
            return (Criteria) this;
        }

        public Criteria andNewCustomerNameIn(List<String> values) {
            addCriterion("new_customer_name in", values, "newCustomerName");
            return (Criteria) this;
        }

        public Criteria andNewCustomerNameNotIn(List<String> values) {
            addCriterion("new_customer_name not in", values, "newCustomerName");
            return (Criteria) this;
        }

        public Criteria andNewCustomerNameBetween(String value1, String value2) {
            addCriterion("new_customer_name between", value1, value2, "newCustomerName");
            return (Criteria) this;
        }

        public Criteria andNewCustomerNameNotBetween(String value1, String value2) {
            addCriterion("new_customer_name not between", value1, value2, "newCustomerName");
            return (Criteria) this;
        }

        public Criteria andTallymanIsNull() {
            addCriterion("tallyman is null");
            return (Criteria) this;
        }

        public Criteria andTallymanIsNotNull() {
            addCriterion("tallyman is not null");
            return (Criteria) this;
        }

        public Criteria andTallymanEqualTo(String value) {
            addCriterion("tallyman =", value, "tallyman");
            return (Criteria) this;
        }

        public Criteria andTallymanNotEqualTo(String value) {
            addCriterion("tallyman <>", value, "tallyman");
            return (Criteria) this;
        }

        public Criteria andTallymanGreaterThan(String value) {
            addCriterion("tallyman >", value, "tallyman");
            return (Criteria) this;
        }

        public Criteria andTallymanGreaterThanOrEqualTo(String value) {
            addCriterion("tallyman >=", value, "tallyman");
            return (Criteria) this;
        }

        public Criteria andTallymanLessThan(String value) {
            addCriterion("tallyman <", value, "tallyman");
            return (Criteria) this;
        }

        public Criteria andTallymanLessThanOrEqualTo(String value) {
            addCriterion("tallyman <=", value, "tallyman");
            return (Criteria) this;
        }

        public Criteria andTallymanLike(String value) {
            addCriterion("tallyman like", value, "tallyman");
            return (Criteria) this;
        }

        public Criteria andTallymanNotLike(String value) {
            addCriterion("tallyman not like", value, "tallyman");
            return (Criteria) this;
        }

        public Criteria andTallymanIn(List<String> values) {
            addCriterion("tallyman in", values, "tallyman");
            return (Criteria) this;
        }

        public Criteria andTallymanNotIn(List<String> values) {
            addCriterion("tallyman not in", values, "tallyman");
            return (Criteria) this;
        }

        public Criteria andTallymanBetween(String value1, String value2) {
            addCriterion("tallyman between", value1, value2, "tallyman");
            return (Criteria) this;
        }

        public Criteria andTallymanNotBetween(String value1, String value2) {
            addCriterion("tallyman not between", value1, value2, "tallyman");
            return (Criteria) this;
        }

        public Criteria andTotalWeightIsNull() {
            addCriterion("total_weight is null");
            return (Criteria) this;
        }

        public Criteria andTotalWeightIsNotNull() {
            addCriterion("total_weight is not null");
            return (Criteria) this;
        }

        public Criteria andTotalWeightEqualTo(Integer value) {
            addCriterion("total_weight =", value, "totalWeight");
            return (Criteria) this;
        }

        public Criteria andTotalWeightNotEqualTo(Integer value) {
            addCriterion("total_weight <>", value, "totalWeight");
            return (Criteria) this;
        }

        public Criteria andTotalWeightGreaterThan(Integer value) {
            addCriterion("total_weight >", value, "totalWeight");
            return (Criteria) this;
        }

        public Criteria andTotalWeightGreaterThanOrEqualTo(Integer value) {
            addCriterion("total_weight >=", value, "totalWeight");
            return (Criteria) this;
        }

        public Criteria andTotalWeightLessThan(Integer value) {
            addCriterion("total_weight <", value, "totalWeight");
            return (Criteria) this;
        }

        public Criteria andTotalWeightLessThanOrEqualTo(Integer value) {
            addCriterion("total_weight <=", value, "totalWeight");
            return (Criteria) this;
        }

        public Criteria andTotalWeightIn(List<Integer> values) {
            addCriterion("total_weight in", values, "totalWeight");
            return (Criteria) this;
        }

        public Criteria andTotalWeightNotIn(List<Integer> values) {
            addCriterion("total_weight not in", values, "totalWeight");
            return (Criteria) this;
        }

        public Criteria andTotalWeightBetween(Integer value1, Integer value2) {
            addCriterion("total_weight between", value1, value2, "totalWeight");
            return (Criteria) this;
        }

        public Criteria andTotalWeightNotBetween(Integer value1, Integer value2) {
            addCriterion("total_weight not between", value1, value2, "totalWeight");
            return (Criteria) this;
        }

        public Criteria andTotalPackageNumIsNull() {
            addCriterion("total_package_num is null");
            return (Criteria) this;
        }

        public Criteria andTotalPackageNumIsNotNull() {
            addCriterion("total_package_num is not null");
            return (Criteria) this;
        }

        public Criteria andTotalPackageNumEqualTo(Integer value) {
            addCriterion("total_package_num =", value, "totalPackageNum");
            return (Criteria) this;
        }

        public Criteria andTotalPackageNumNotEqualTo(Integer value) {
            addCriterion("total_package_num <>", value, "totalPackageNum");
            return (Criteria) this;
        }

        public Criteria andTotalPackageNumGreaterThan(Integer value) {
            addCriterion("total_package_num >", value, "totalPackageNum");
            return (Criteria) this;
        }

        public Criteria andTotalPackageNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("total_package_num >=", value, "totalPackageNum");
            return (Criteria) this;
        }

        public Criteria andTotalPackageNumLessThan(Integer value) {
            addCriterion("total_package_num <", value, "totalPackageNum");
            return (Criteria) this;
        }

        public Criteria andTotalPackageNumLessThanOrEqualTo(Integer value) {
            addCriterion("total_package_num <=", value, "totalPackageNum");
            return (Criteria) this;
        }

        public Criteria andTotalPackageNumIn(List<Integer> values) {
            addCriterion("total_package_num in", values, "totalPackageNum");
            return (Criteria) this;
        }

        public Criteria andTotalPackageNumNotIn(List<Integer> values) {
            addCriterion("total_package_num not in", values, "totalPackageNum");
            return (Criteria) this;
        }

        public Criteria andTotalPackageNumBetween(Integer value1, Integer value2) {
            addCriterion("total_package_num between", value1, value2, "totalPackageNum");
            return (Criteria) this;
        }

        public Criteria andTotalPackageNumNotBetween(Integer value1, Integer value2) {
            addCriterion("total_package_num not between", value1, value2, "totalPackageNum");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("status like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("status not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andCreateCodeIsNull() {
            addCriterion("create_code is null");
            return (Criteria) this;
        }

        public Criteria andCreateCodeIsNotNull() {
            addCriterion("create_code is not null");
            return (Criteria) this;
        }

        public Criteria andCreateCodeEqualTo(String value) {
            addCriterion("create_code =", value, "createCode");
            return (Criteria) this;
        }

        public Criteria andCreateCodeNotEqualTo(String value) {
            addCriterion("create_code <>", value, "createCode");
            return (Criteria) this;
        }

        public Criteria andCreateCodeGreaterThan(String value) {
            addCriterion("create_code >", value, "createCode");
            return (Criteria) this;
        }

        public Criteria andCreateCodeGreaterThanOrEqualTo(String value) {
            addCriterion("create_code >=", value, "createCode");
            return (Criteria) this;
        }

        public Criteria andCreateCodeLessThan(String value) {
            addCriterion("create_code <", value, "createCode");
            return (Criteria) this;
        }

        public Criteria andCreateCodeLessThanOrEqualTo(String value) {
            addCriterion("create_code <=", value, "createCode");
            return (Criteria) this;
        }

        public Criteria andCreateCodeLike(String value) {
            addCriterion("create_code like", value, "createCode");
            return (Criteria) this;
        }

        public Criteria andCreateCodeNotLike(String value) {
            addCriterion("create_code not like", value, "createCode");
            return (Criteria) this;
        }

        public Criteria andCreateCodeIn(List<String> values) {
            addCriterion("create_code in", values, "createCode");
            return (Criteria) this;
        }

        public Criteria andCreateCodeNotIn(List<String> values) {
            addCriterion("create_code not in", values, "createCode");
            return (Criteria) this;
        }

        public Criteria andCreateCodeBetween(String value1, String value2) {
            addCriterion("create_code between", value1, value2, "createCode");
            return (Criteria) this;
        }

        public Criteria andCreateCodeNotBetween(String value1, String value2) {
            addCriterion("create_code not between", value1, value2, "createCode");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("create_date is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("create_date is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(Date value) {
            addCriterion("create_date =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(Date value) {
            addCriterion("create_date <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(Date value) {
            addCriterion("create_date >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("create_date >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(Date value) {
            addCriterion("create_date <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(Date value) {
            addCriterion("create_date <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<Date> values) {
            addCriterion("create_date in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<Date> values) {
            addCriterion("create_date not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(Date value1, Date value2) {
            addCriterion("create_date between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(Date value1, Date value2) {
            addCriterion("create_date not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andUpdateCodeIsNull() {
            addCriterion("update_code is null");
            return (Criteria) this;
        }

        public Criteria andUpdateCodeIsNotNull() {
            addCriterion("update_code is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateCodeEqualTo(String value) {
            addCriterion("update_code =", value, "updateCode");
            return (Criteria) this;
        }

        public Criteria andUpdateCodeNotEqualTo(String value) {
            addCriterion("update_code <>", value, "updateCode");
            return (Criteria) this;
        }

        public Criteria andUpdateCodeGreaterThan(String value) {
            addCriterion("update_code >", value, "updateCode");
            return (Criteria) this;
        }

        public Criteria andUpdateCodeGreaterThanOrEqualTo(String value) {
            addCriterion("update_code >=", value, "updateCode");
            return (Criteria) this;
        }

        public Criteria andUpdateCodeLessThan(String value) {
            addCriterion("update_code <", value, "updateCode");
            return (Criteria) this;
        }

        public Criteria andUpdateCodeLessThanOrEqualTo(String value) {
            addCriterion("update_code <=", value, "updateCode");
            return (Criteria) this;
        }

        public Criteria andUpdateCodeLike(String value) {
            addCriterion("update_code like", value, "updateCode");
            return (Criteria) this;
        }

        public Criteria andUpdateCodeNotLike(String value) {
            addCriterion("update_code not like", value, "updateCode");
            return (Criteria) this;
        }

        public Criteria andUpdateCodeIn(List<String> values) {
            addCriterion("update_code in", values, "updateCode");
            return (Criteria) this;
        }

        public Criteria andUpdateCodeNotIn(List<String> values) {
            addCriterion("update_code not in", values, "updateCode");
            return (Criteria) this;
        }

        public Criteria andUpdateCodeBetween(String value1, String value2) {
            addCriterion("update_code between", value1, value2, "updateCode");
            return (Criteria) this;
        }

        public Criteria andUpdateCodeNotBetween(String value1, String value2) {
            addCriterion("update_code not between", value1, value2, "updateCode");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNull() {
            addCriterion("update_date is null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNotNull() {
            addCriterion("update_date is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateEqualTo(String value) {
            addCriterion("update_date =", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotEqualTo(String value) {
            addCriterion("update_date <>", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThan(String value) {
            addCriterion("update_date >", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThanOrEqualTo(String value) {
            addCriterion("update_date >=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThan(String value) {
            addCriterion("update_date <", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThanOrEqualTo(String value) {
            addCriterion("update_date <=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLike(String value) {
            addCriterion("update_date like", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotLike(String value) {
            addCriterion("update_date not like", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIn(List<String> values) {
            addCriterion("update_date in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotIn(List<String> values) {
            addCriterion("update_date not in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateBetween(String value1, String value2) {
            addCriterion("update_date between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotBetween(String value1, String value2) {
            addCriterion("update_date not between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andGoodIdIsNull() {
            addCriterion("good_id is null");
            return (Criteria) this;
        }

        public Criteria andGoodIdIsNotNull() {
            addCriterion("good_id is not null");
            return (Criteria) this;
        }

        public Criteria andGoodIdEqualTo(String value) {
            addCriterion("good_id =", value, "goodId");
            return (Criteria) this;
        }

        public Criteria andGoodIdNotEqualTo(String value) {
            addCriterion("good_id <>", value, "goodId");
            return (Criteria) this;
        }

        public Criteria andGoodIdGreaterThan(String value) {
            addCriterion("good_id >", value, "goodId");
            return (Criteria) this;
        }

        public Criteria andGoodIdGreaterThanOrEqualTo(String value) {
            addCriterion("good_id >=", value, "goodId");
            return (Criteria) this;
        }

        public Criteria andGoodIdLessThan(String value) {
            addCriterion("good_id <", value, "goodId");
            return (Criteria) this;
        }

        public Criteria andGoodIdLessThanOrEqualTo(String value) {
            addCriterion("good_id <=", value, "goodId");
            return (Criteria) this;
        }

        public Criteria andGoodIdLike(String value) {
            addCriterion("good_id like", value, "goodId");
            return (Criteria) this;
        }

        public Criteria andGoodIdNotLike(String value) {
            addCriterion("good_id not like", value, "goodId");
            return (Criteria) this;
        }

        public Criteria andGoodIdIn(List<String> values) {
            addCriterion("good_id in", values, "goodId");
            return (Criteria) this;
        }

        public Criteria andGoodIdNotIn(List<String> values) {
            addCriterion("good_id not in", values, "goodId");
            return (Criteria) this;
        }

        public Criteria andGoodIdBetween(String value1, String value2) {
            addCriterion("good_id between", value1, value2, "goodId");
            return (Criteria) this;
        }

        public Criteria andGoodIdNotBetween(String value1, String value2) {
            addCriterion("good_id not between", value1, value2, "goodId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_stock_change
     *
     * @mbggenerated do_not_delete_during_merge Wed Apr 22 20:10:30 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_stock_change
     *
     * @mbggenerated Wed Apr 22 20:10:30 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}